# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Docker@2
  inputs:
    repository: $(DOCKER_REPOSITORY_NAME)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: ECRPullImage@1
  inputs:
    awsCredentials: 'Default'
    regionName: 'us-west-2'
    repository: 'webapplication18'
    imageSource: 'imagetag'
    imageTag: '637756376999017153'
  
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'Default'
    regionName: 'us-west-2'
    imageSource: 'imagename'
    sourceImageName: $(DOCKER_REPOSITORY_NAME)
    sourceImageTag: $(Build.BuildId)
    repositoryName: $(DOCKER_REPOSITORY_NAME)
    pushTag: latest
    autoCreateRepository: true
    removeDockerImage: true
